"""GET /judge — Evidence-first technical view for Razorpay evaluators.

Design: Same token system as product_page.py. Shows architecture, live
proof, test evidence, and the demo flow guide. No fake numbers — everything
reads from truth.json which is generated by running the actual system.
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()


def _load_truth() -> dict:
    truth_path = Path(__file__).resolve().parents[3] / "docs" / "generated" / "truth.json"
    try:
        return json.loads(truth_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _t(truth: dict, section: str, key: str, default: str = "—") -> str:
    v = (truth.get(section) or {}).get(key)
    return default if v is None else str(v)


def render_judge_page() -> str:
    from .. import config as app_config
    from ..money import snapshot as money_snapshot

    truth = _load_truth()
    cfg = app_config.status_summary()
    is_simulated = not cfg.get("payment_configured", False)
    money_calls = money_snapshot().get("total", 0)

    t = lambda s, k, d="—": _t(truth, s, k, d)
    tests_passed = t("tests", "passed")
    tests_skipped = t("tests", "skipped")
    attacks_blocked = t("attacks", "blocked")
    gateway_latency = t("gateway", "p95_ms")
    money_boundary = t("money_boundary", "razorpay_calls_from_llm_context", "0")

    razorpay_status = (
        '<span style="color:var(--teal);font-weight:650">● Razorpay test mode active</span>'
        if not is_simulated else
        '<span style="color:var(--amber);font-weight:650">● Simulated — add Razorpay test keys to .env</span>'
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SELLABLE — Judge View</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='8' fill='%230D9488'/%3E%3Cpath d='M8 16l5 5 9-9' stroke='white' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E">
<style>
:root{{
  --bg:#F7F8FC;--surface:#FFFFFF;--surface-2:#F0F2F9;--border:#E2E8F0;--border-2:#CBD5E1;
  --navy:#0F1729;--slate:#475569;--muted:#94A3B8;--ink:#1E293B;
  --violet:#6C47FF;--violet-dim:#EDE9FF;--teal:#0D9488;--teal-dim:#CCFBF1;
  --amber:#D97706;--amber-dim:#FEF3C7;--red:#DC2626;--red-dim:#FEE2E2;
  --r:12px;--r-lg:18px;--sans:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
  --mono:ui-monospace,"SF Mono","Cascadia Code",Menlo,monospace;
  --shadow:0 4px 12px rgba(15,23,41,.08),0 2px 4px rgba(15,23,41,.06);
}}
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
html{{scroll-behavior:smooth}}
body{{
  background:var(--bg);color:var(--ink);font-family:var(--sans);
  font-size:15px;line-height:1.65;-webkit-font-smoothing:antialiased;
}}
a{{color:var(--violet);text-decoration:none}}
a:hover{{text-decoration:underline}}
button{{cursor:pointer;font:inherit;border:none;background:none}}

.nav{{
  position:sticky;top:0;z-index:100;
  background:rgba(247,248,252,.9);backdrop-filter:blur(14px);
  border-bottom:1px solid var(--border);
}}
.nav-inner{{
  max-width:1100px;margin:0 auto;padding:0 24px;
  display:flex;align-items:center;gap:16px;height:56px;
}}
.brand{{font-weight:800;font-size:16px;letter-spacing:-0.04em;color:var(--navy)}}
.back-link{{
  font-size:13px;color:var(--slate);display:flex;align-items:center;gap:4px;
}}
.back-link:hover{{color:var(--violet)}}
.judge-badge{{
  font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;
  color:var(--teal);background:var(--teal-dim);
  border:1px solid rgba(13,148,136,.2);border-radius:999px;padding:4px 12px;
  margin-left:auto;
}}

.wrap{{max-width:1100px;margin:0 auto;padding:0 24px}}

.page-header{{padding:48px 0 40px;border-bottom:1px solid var(--border)}}
.page-header h1{{
  font-size:clamp(28px,4vw,44px);font-weight:840;letter-spacing:-0.04em;
  color:var(--navy);margin-bottom:12px;
}}
.page-header p{{font-size:16px;color:var(--slate);max-width:60ch;line-height:1.7}}
.mode-tag{{
  display:inline-block;font-size:12px;margin-top:16px;
}}

.section{{padding:40px 0}}
.section+.section{{border-top:1px solid var(--border)}}
.section-eyebrow{{
  font-size:11px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;
  color:var(--muted);margin-bottom:8px;
}}
.section-title{{
  font-size:22px;font-weight:780;letter-spacing:-0.03em;color:var(--navy);
  margin-bottom:16px;
}}
.section-body{{font-size:14.5px;color:var(--slate);line-height:1.75;max-width:68ch}}

/* stat grid */
.stat-grid{{
  display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));
  gap:14px;margin-top:24px;
}}
.stat-card{{
  background:var(--surface);border:1px solid var(--border);
  border-radius:var(--r);padding:18px 20px;
  box-shadow:0 1px 3px rgba(15,23,41,.06);
}}
.stat-number{{
  font-size:32px;font-weight:820;letter-spacing:-0.05em;
  color:var(--navy);line-height:1;margin-bottom:6px;
}}
.stat-number.violet{{color:var(--violet)}}
.stat-number.teal{{color:var(--teal)}}
.stat-number.amber{{color:var(--amber)}}
.stat-label{{font-size:12px;color:var(--muted);font-weight:500;line-height:1.4}}
.stat-source{{font-size:10.5px;font-family:var(--mono);color:var(--border-2);margin-top:6px}}

/* pipeline diagram */
.arch-flow{{
  display:flex;align-items:center;gap:0;flex-wrap:wrap;
  margin:24px 0;
}}
.arch-node{{
  background:var(--surface);border:1.5px solid var(--border);
  border-radius:var(--r);padding:12px 16px;min-width:110px;text-align:center;
}}
.arch-node.ai{{border-color:var(--violet);background:var(--violet-dim)}}
.arch-node.gate{{border-color:var(--navy);background:var(--navy);color:#fff}}
.arch-node.user{{border-color:var(--teal);background:var(--teal-dim)}}
.arch-node.pay{{border-color:var(--amber);background:var(--amber-dim)}}
.arch-label{{font-size:11px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}}
.arch-sub{{font-size:10.5px;color:var(--muted);margin-top:3px;line-height:1.3}}
.arch-node.gate .arch-sub{{color:rgba(255,255,255,.55)}}
.arch-arrow{{color:var(--border-2);font-size:18px;padding:0 6px;flex-shrink:0}}

/* proof box */
.proof-box{{
  background:var(--surface);border:1px solid var(--border);border-radius:var(--r);
  overflow:hidden;margin-top:20px;
}}
.proof-box-header{{
  display:flex;align-items:center;justify-content:space-between;
  padding:14px 18px;border-bottom:1px solid var(--border);
  background:var(--surface-2);
}}
.proof-box-title{{font-size:13px;font-weight:700;color:var(--navy)}}
.proof-run-btn{{
  height:32px;padding:0 16px;border-radius:999px;
  border:1px solid var(--violet);color:var(--violet);font-size:12.5px;font-weight:600;
  background:transparent;transition:all .15s;
}}
.proof-run-btn:hover{{background:var(--violet-dim)}}
.proof-body{{padding:16px 18px;font-family:var(--mono);font-size:12.5px;color:var(--slate);line-height:1.8}}
.proof-key{{color:var(--muted)}}
.proof-val{{color:var(--navy);font-weight:600}}
.proof-val.ok{{color:var(--teal)}}
.proof-val.warn{{color:var(--amber)}}
.proof-val.zero{{color:var(--teal)}}

/* invariant list */
.invariant-list{{display:grid;gap:10px;margin-top:20px}}
.invariant-row{{
  display:flex;align-items:flex-start;gap:12px;padding:14px 18px;
  background:var(--surface);border:1px solid var(--border);border-radius:var(--r);
}}
.inv-icon{{
  width:22px;height:22px;border-radius:50%;flex-shrink:0;
  display:flex;align-items:center;justify-content:center;font-size:11px;margin-top:1px;
}}
.inv-icon.ok{{background:var(--teal-dim);color:var(--teal)}}
.inv-icon.warn{{background:var(--amber-dim);color:var(--amber)}}
.inv-title{{font-size:13.5px;font-weight:650;color:var(--navy);margin-bottom:3px}}
.inv-body{{font-size:12.5px;color:var(--slate);line-height:1.6}}
.inv-code{{
  font-family:var(--mono);font-size:11px;color:var(--muted);margin-top:4px;
}}

/* demo steps */
.demo-steps{{display:grid;gap:12px;margin-top:20px}}
.demo-step{{
  display:flex;gap:16px;padding:16px 18px;
  background:var(--surface);border:1px solid var(--border);border-radius:var(--r);
  align-items:flex-start;
}}
.demo-time{{
  font-family:var(--mono);font-size:11px;color:var(--muted);
  background:var(--surface-2);border-radius:999px;padding:3px 9px;
  white-space:nowrap;flex-shrink:0;margin-top:2px;
}}
.demo-step-content{{flex:1}}
.demo-step-title{{font-size:14px;font-weight:650;color:var(--navy);margin-bottom:4px}}
.demo-step-body{{font-size:13px;color:var(--slate);line-height:1.6}}
.demo-step-action{{
  margin-top:8px;font-size:12px;font-weight:600;color:var(--violet);
  font-family:var(--mono);
}}

/* quick links */
.link-grid{{
  display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));
  gap:12px;margin-top:20px;
}}
.link-card{{
  display:flex;align-items:center;gap:12px;padding:14px 18px;
  background:var(--surface);border:1px solid var(--border);border-radius:var(--r);
  text-decoration:none;color:var(--ink);transition:all .18s;
}}
.link-card:hover{{border-color:var(--violet);transform:translateY(-2px);box-shadow:var(--shadow)}}
.link-icon{{
  width:32px;height:32px;border-radius:8px;flex-shrink:0;
  display:flex;align-items:center;justify-content:center;font-size:16px;
}}
.link-icon.violet{{background:var(--violet-dim)}}
.link-icon.teal{{background:var(--teal-dim)}}
.link-icon.amber{{background:var(--amber-dim)}}
.link-text-title{{font-size:13.5px;font-weight:650;color:var(--navy)}}
.link-text-sub{{font-size:12px;color:var(--muted)}}

/* live check */
.live-check-row{{display:flex;gap:16px;flex-wrap:wrap;margin-top:20px}}
.check-btn{{
  height:40px;padding:0 20px;border-radius:var(--r);
  font-size:13.5px;font-weight:650;transition:all .18s;
  display:inline-flex;align-items:center;gap:8px;
}}
.btn-primary{{background:var(--navy);color:#fff}}
.btn-primary:hover{{background:var(--violet)}}
.btn-outline{{border:1.5px solid var(--border);color:var(--slate);background:transparent}}
.btn-outline:hover{{border-color:var(--violet);color:var(--violet)}}

.proof-output{{
  margin-top:16px;font-family:var(--mono);font-size:12px;
  background:var(--navy);color:#a7c3ff;padding:16px 18px;
  border-radius:var(--r);line-height:1.8;display:none;max-height:320px;overflow-y:auto;
}}
.proof-output.show{{display:block}}

@media(max-width:680px){{
  .arch-flow{{flex-direction:column;align-items:flex-start}}
  .arch-arrow{{transform:rotate(90deg)}}
  .stat-grid{{grid-template-columns:repeat(2,1fr)}}
  .wrap{{padding:0 16px}}
}}
</style>
</head>
<body>

<nav class="nav">
  <div class="nav-inner">
    <div class="brand">SELLABLE</div>
    <a class="back-link" href="/">
      <svg width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5"><path d="M19 12H5M12 5l-7 7 7 7"/></svg>
      Back to shop
    </a>
    <span class="judge-badge">Judge View</span>
  </div>
</nav>

<div class="wrap">

  <div class="page-header">
    <h1>Technical Evidence</h1>
    <p>Everything this project claims is backed by code you can run. Use this page to inspect
       the security boundary, replay attacks, and verify the failure-recovery story.</p>
    <div class="mode-tag">{razorpay_status}</div>
  </div>

  <!-- ── LIVE NUMBERS ── -->
  <div class="section">
    <div class="section-eyebrow">Evidence — generated by running the system</div>
    <div class="section-title">What the tests actually prove</div>
    <div class="stat-grid">
      <div class="stat-card">
        <div class="stat-number teal">{tests_passed}</div>
        <div class="stat-label">Tests passing</div>
        <div class="stat-source">pytest · docs/generated/truth.json</div>
      </div>
      <div class="stat-card">
        <div class="stat-number violet">{attacks_blocked}</div>
        <div class="stat-label">Attack scenarios blocked by gateway</div>
        <div class="stat-source">tests/invariants/</div>
      </div>
      <div class="stat-card">
        <div class="stat-number teal">{money_boundary}</div>
        <div class="stat-label">Razorpay calls from LLM context</div>
        <div class="stat-source">apps/api/money.py snapshot</div>
      </div>
      <div class="stat-card">
        <div class="stat-number violet">{gateway_latency}<span style="font-size:16px;font-weight:400"> ms</span></div>
        <div class="stat-label">Gateway decision p95 latency</div>
        <div class="stat-source">100 evaluations · truth.json</div>
      </div>
    </div>
  </div>

  <!-- ── ARCHITECTURE ── -->
  <div class="section">
    <div class="section-eyebrow">Architecture</div>
    <div class="section-title">The trust boundary, made visible</div>
    <div class="section-body">
      The central thesis: AI can reason about commerce, but deterministic controls
      ensure that reasoning can never become uncontrolled money movement.
      The gateway has no network access, no LLM imports, and no file I/O.
      It cannot be convinced — it can only be computed.
    </div>

    <div class="arch-flow">
      <div class="arch-node ai">
        <div class="arch-label" style="color:var(--violet)">AI Buyer</div>
        <div class="arch-sub">LLM reasons &amp; proposes</div>
      </div>
      <div class="arch-arrow">→</div>
      <div class="arch-node gate">
        <div class="arch-label">Gateway</div>
        <div class="arch-sub">Deterministic · R1–R12</div>
      </div>
      <div class="arch-arrow">→</div>
      <div class="arch-node user">
        <div class="arch-label" style="color:var(--teal)">You</div>
        <div class="arch-sub">Sign the mandate</div>
      </div>
      <div class="arch-arrow">→</div>
      <div class="arch-node pay">
        <div class="arch-label" style="color:var(--amber)">Razorpay</div>
        <div class="arch-sub">Executes &amp; webhooks</div>
      </div>
      <div class="arch-arrow">→</div>
      <div class="arch-node">
        <div class="arch-label">Reconcile</div>
        <div class="arch-sub">Unknown → truth</div>
      </div>
    </div>

    <div class="invariant-list">
      <div class="invariant-row">
        <div class="inv-icon ok">✓</div>
        <div>
          <div class="inv-title">Gateway is deterministic and isolated</div>
          <div class="inv-body">No LLM SDK, no network calls, no file I/O. Decision is computed from the binding alone.</div>
          <div class="inv-code">tests/invariants/test_gateway_purity.py — AST parse + 100-run determinism</div>
        </div>
      </div>
      <div class="invariant-row">
        <div class="inv-icon ok">✓</div>
        <div>
          <div class="inv-title">Agent never touches signing keys or payment SDK</div>
          <div class="inv-body">Agent code imports are statically verified. The LLM runner cannot reach razorpay_client.</div>
          <div class="inv-code">tests/invariants/test_agent_custody.py</div>
        </div>
      </div>
      <div class="invariant-row">
        <div class="inv-icon ok">✓</div>
        <div>
          <div class="inv-title">REMOTE_ATTEMPTED written to disk before the network call</div>
          <div class="inv-body">A crash between commit and response leaves the execution in RECONCILIATION_REQUIRED, not lost.</div>
          <div class="inv-code">apps/api/execution.py · tests/execution/test_execution_state_machine.py</div>
        </div>
      </div>
      <div class="invariant-row">
        <div class="inv-icon ok">✓</div>
        <div>
          <div class="inv-title">Authorization replay blocked</div>
          <div class="inv-body">Each approval binding is single-use. The gateway rejects a second use of the same binding.</div>
          <div class="inv-code">tests/gateway/test_binding_field_matrix.py</div>
        </div>
      </div>
      <div class="invariant-row">
        <div class="inv-icon ok">✓</div>
        <div>
          <div class="inv-title">Prices are server-authoritative</div>
          <div class="inv-body">The checkout route ignores any amount field from the client. Price always comes from the catalog.</div>
          <div class="inv-code">apps/api/discovery/api.py — amount_paise field explicitly ignored</div>
        </div>
      </div>
    </div>
  </div>

  <!-- ── LIVE PROOF ── -->
  <div class="section">
    <div class="section-eyebrow">Live Verification</div>
    <div class="section-title">Run it yourself</div>

    <div class="proof-box">
      <div class="proof-box-header">
        <span class="proof-box-title">Gateway purity proof</span>
        <button class="proof-run-btn" onclick="fetchProof()">Fetch live</button>
      </div>
      <div class="proof-body" id="proof-body">
        <span class="proof-key">status</span> &nbsp; <span class="proof-val ok" id="pf-status">—</span><br>
        <span class="proof-key">source_sha256</span> &nbsp; <span class="proof-val" id="pf-hash">—</span><br>
        <span class="proof-key">forbidden_imports_found</span> &nbsp; <span class="proof-val" id="pf-imports">—</span><br>
        <span class="proof-key">determinism_evaluations</span> &nbsp; <span class="proof-val" id="pf-det">—</span><br>
        <span class="proof-key">razorpay_calls_from_llm</span> &nbsp; <span class="proof-val zero" id="pf-money">{money_calls}</span>
      </div>
    </div>

    <div class="live-check-row">
      <a href="/gateway/proof" class="check-btn btn-primary" target="_blank">View gateway proof →</a>
      <a href="/audit" class="check-btn btn-outline" target="_blank">Audit hash chain →</a>
      <a href="/health" class="check-btn btn-outline" target="_blank">Health →</a>
      <a href="/docs" class="check-btn btn-outline" target="_blank">OpenAPI →</a>
    </div>
  </div>

  <!-- ── DEMO GUIDE ── -->
  <div class="section">
    <div class="section-eyebrow">5-Minute Demo</div>
    <div class="section-title">Recommended evaluation flow</div>

    <div class="demo-steps">
      <div class="demo-step">
        <span class="demo-time">0:00</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Open the shop</div>
          <div class="demo-step-body">Navigate to <code>/</code>. No login, no setup. One search bar.</div>
          <div class="demo-step-action">→ GET /</div>
        </div>
      </div>
      <div class="demo-step">
        <span class="demo-time">0:30</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Search for a product</div>
          <div class="demo-step-body">Type "cricket bat under ₹3000". The pipeline rail appears — Discover lights up as the AI queries live retail sources via Bing RSS and price-extracts results.</div>
          <div class="demo-step-action">→ POST /discovery/search</div>
        </div>
      </div>
      <div class="demo-step">
        <span class="demo-time">1:00</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Evidence cards appear</div>
          <div class="demo-step-body">Each card shows its source domain (whitelist-verified retail only), evidence class (OBSERVED / FX / UNVERIFIED), and a link to the original URL. No invented prices.</div>
        </div>
      </div>
      <div class="demo-step">
        <span class="demo-time">1:30</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Try the gateway probe</div>
          <div class="demo-step-body">Click "Try injecting this → gateway will reject it". A real over-budget SKU from the catalog is sent through checkout. The gateway blocks it. Razorpay calls = 0.</div>
          <div class="demo-step-action">→ POST /discovery/checkout (budget violation → 422)</div>
        </div>
      </div>
      <div class="demo-step">
        <span class="demo-time">2:30</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Authorize a valid purchase</div>
          <div class="demo-step-body">Click "Review &amp; Authorize" on the recommended item. The modal shows the AI's reasoning, all gateway checks, and the demo wallet disclaimer. Click Approve.</div>
          <div class="demo-step-action">→ POST /discovery/checkout (valid path)</div>
        </div>
      </div>
      <div class="demo-step">
        <span class="demo-time">3:30</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Inject a provider timeout</div>
          <div class="demo-step-body">Before approving again, click "Provider timeout" in the fault bar. Execute. The state machine reaches RECONCILIATION_REQUIRED — not FAILED, not SUCCESS. The outcome is genuinely unknown.</div>
          <div class="demo-step-action">→ execution.state = RECONCILIATION_REQUIRED</div>
        </div>
      </div>
      <div class="demo-step">
        <span class="demo-time">4:00</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Reconcile</div>
          <div class="demo-step-body">Click "Reconcile — query provider state". The system queries the provider and resolves to EXECUTED or NOT_EXECUTED.</div>
          <div class="demo-step-action">→ POST /discovery/reconcile/{{execution_id}}</div>
        </div>
      </div>
      <div class="demo-step">
        <span class="demo-time">4:40</span>
        <div class="demo-step-content">
          <div class="demo-step-title">Show the audit chain</div>
          <div class="demo-step-body">Every event — search, proposal, approval, execution, reconciliation — is hash-chained. Open /audit to show the chain is intact.</div>
          <div class="demo-step-action">→ GET /audit</div>
        </div>
      </div>
    </div>
  </div>

  <!-- ── QUICK LINKS ── -->
  <div class="section">
    <div class="section-eyebrow">Evidence Links</div>
    <div class="section-title">Everything in one place</div>
    <div class="link-grid">
      <a class="link-card" href="/gateway/proof" target="_blank">
        <div class="link-icon violet">🛡</div>
        <div>
          <div class="link-text-title">Gateway proof</div>
          <div class="link-text-sub">SHA-256, imports, determinism</div>
        </div>
      </a>
      <a class="link-card" href="/audit" target="_blank">
        <div class="link-icon teal">🔗</div>
        <div>
          <div class="link-text-title">Audit hash chain</div>
          <div class="link-text-sub">Every event, cryptographically linked</div>
        </div>
      </a>
      <a class="link-card" href="/attack-ui" target="_blank">
        <div class="link-icon violet">⚔</div>
        <div>
          <div class="link-text-title">Attack scenarios</div>
          <div class="link-text-sub">Prompt injection, replay, escalation</div>
        </div>
      </a>
      <a class="link-card" href="/diagnostics" target="_blank">
        <div class="link-icon amber">📊</div>
        <div>
          <div class="link-text-title">System diagnostics</div>
          <div class="link-text-sub">Config, providers, state</div>
        </div>
      </a>
      <a class="link-card" href="/docs" target="_blank">
        <div class="link-icon teal">📖</div>
        <div>
          <div class="link-text-title">OpenAPI spec</div>
          <div class="link-text-sub">All routes, schemas, examples</div>
        </div>
      </a>
      <a class="link-card" href="https://github.com/HarshDubey23/SELLABLE" target="_blank" rel="noopener">
        <div class="link-icon violet">⌥</div>
        <div>
          <div class="link-text-title">GitHub repository</div>
          <div class="link-text-sub">Source, tests, docs</div>
        </div>
      </a>
    </div>
  </div>

  <!-- ── KNOWN LIMITATIONS ── -->
  <div class="section">
    <div class="section-eyebrow">Known Limitations</div>
    <div class="section-title">What this is not</div>
    <div class="invariant-list">
      <div class="invariant-row">
        <div class="inv-icon warn">!</div>
        <div>
          <div class="inv-title">Demo wallet — not a real external wallet</div>
          <div class="inv-body">The authorization step simulates a user mandate in-process. In production this would be a hardware-signed mandate from an external wallet. The security claim holds in both cases — the LLM cannot bypass it — but the demo does not use real wallet hardware.</div>
        </div>
      </div>
      <div class="invariant-row">
        <div class="inv-icon warn">!</div>
        <div>
          <div class="inv-title">Razorpay test mode only</div>
          <div class="inv-body">All payment execution uses Razorpay test keys. No real money moves. Real credentials can be substituted via .env without code changes.</div>
        </div>
      </div>
      <div class="invariant-row">
        <div class="inv-icon warn">!</div>
        <div>
          <div class="inv-title">Single-node SQLite deployment</div>
          <div class="inv-body">The execution state machine and audit chain use SQLite with WAL mode. Production would need Postgres. The durability guarantees are identical; the concurrency ceiling differs.</div>
        </div>
      </div>
      <div class="invariant-row">
        <div class="inv-icon warn">!</div>
        <div>
          <div class="inv-title">Live discovery depends on external availability</div>
          <div class="inv-body">Product discovery queries real retail URLs via Bing RSS. If those sources are unavailable, search returns SEARCH_UNAVAILABLE — it does not fall back to invented prices.</div>
        </div>
      </div>
    </div>
  </div>

</div><!-- /wrap -->

<footer style="border-top:1px solid var(--border);padding:24px;max-width:1100px;margin:0 auto;
               display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;
               gap:16px;font-size:12.5px;color:var(--muted)">
  <span>SELLABLE · Razorpay AI Buildathon 2026 · Harsh Dubey · KIET</span>
  <div style="display:flex;gap:20px">
    <a href="/" style="color:var(--muted)">Shop</a>
    <a href="/audit" style="color:var(--muted)">Audit</a>
    <a href="/health" style="color:var(--muted)">Health</a>
    <a href="https://github.com/HarshDubey23/SELLABLE" style="color:var(--muted)" target="_blank">GitHub</a>
  </div>
</footer>

<script>
async function fetchProof() {{
  try {{
    const r = await fetch('/gateway/proof');
    const d = await r.json();
    document.getElementById('pf-status').textContent = d.status || '—';
    document.getElementById('pf-hash').textContent = (d.source_sha256 || '—').slice(0,32) + '…';
    document.getElementById('pf-imports').textContent = JSON.stringify(d.forbidden_imports_found ?? []);
    document.getElementById('pf-det').textContent = d.determinism_evaluations ?? '—';
    document.getElementById('pf-money').textContent = d.razorpay_calls_from_llm_context ?? '0';
  }} catch(e) {{
    document.getElementById('pf-status').textContent = 'error: ' + e.message;
  }}
}}
fetchProof();
</script>
</body>
</html>"""


@router.get("/judge", response_class=HTMLResponse)
@router.get("/demo/judge", response_class=HTMLResponse)
async def judge_page() -> HTMLResponse:
    return HTMLResponse(render_judge_page())
