#!/usr/bin/env python3
"""SELLABLE — the one command.

    python run.py

Creates .env if missing, installs dependencies into .venv if they are not
importable, starts the API, waits for a real health check, runs smoke
checks against live endpoints, and prints where to go.

Standard library only, ASCII output only (Windows consoles default to
cp1252 and will crash on box-drawing characters). Safe to re-run: every
step is idempotent.

Options:
    --port N        listen on a specific port (default 8000, auto-advances
                    if busy unless you pass one explicitly)
    --host H        bind address (default 127.0.0.1)
    --no-browser    do not open a browser window
    --check         start, verify, print the report, then exit non-zero on
                    failure. Intended for CI and for "does this actually
                    work on a clean checkout" verification.
"""
from __future__ import annotations

import argparse
import json
import os
import secrets
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
import webbrowser
from pathlib import Path

REPO = Path(__file__).resolve().parent
ENV_PATH = REPO / ".env"
REQUIREMENTS = REPO / "apps" / "api" / "requirements.txt"
VENV = REPO / ".venv"
MIN_PYTHON = (3, 10)


def say(tag: str, msg: str) -> None:
    print(f"[{tag}] {msg}", flush=True)


def die(msg: str, remedy: str = "") -> None:
    print(f"\n[ERROR] {msg}", file=sys.stderr)
    if remedy:
        print(f"[FIX]   {remedy}", file=sys.stderr)
    sys.exit(1)


# ------------------------------------------------------------------ setup

def check_python() -> None:
    if sys.version_info < MIN_PYTHON:
        die(f"Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ is required; "
            f"found {sys.version.split()[0]}",
            "install a newer Python from https://python.org and re-run")


# Secrets the app cannot start meaningfully without. Each is generated
# locally; none of them is a third-party credential.
GENERATED_SECRETS = ("MISSION_HMAC_KEY", "USER_MANDATE_KEY", "APP_API_KEY")

# Values that ship in .env.example and must never be mistaken for real
# configuration. Kept in step with apps/api/config.PLACEHOLDER_VALUES.
PLACEHOLDERS = {
    "", "rzp_test_xxxxxxxx", "your_secret_here", "your_webhook_secret_here",
    "generate_with_python_secrets_token_hex_32",
    "your_openrouter_keys_comma_separated", "your_gemini_api_key_here",
    "your_openrouter_key_here", "changeme",
}


def _read_env_file() -> dict[str, str]:
    values: dict[str, str] = {}
    if not ENV_PATH.exists():
        return values
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, raw = line.partition("=")
        # strip inline comments and quotes the way python-dotenv does
        val = raw.split("#", 1)[0].strip().strip('"').strip("'")
        values[key.strip()] = val
    return values


def repair_env() -> None:
    """Fill in any locally-generated secret that is absent or a placeholder.

    A .env copied from .env.example has values like
    `generate_with_python_secrets_token_hex_32`, which the app correctly
    refuses to treat as a key. Without this repair the server boots with
    R9 unable to verify anything and INV-3 unable to check a mandate — a
    confusing half-broken state. We top the file up instead.
    """
    existing = _read_env_file()
    missing = [k for k in GENERATED_SECRETS
               if existing.get(k, "") in PLACEHOLDERS]
    if not missing:
        say("SETUP", ".env found")
        return

    say("SETUP", f".env is missing usable values for {', '.join(missing)}"
                 " - generating them")
    with ENV_PATH.open("a", encoding="utf-8") as fh:
        fh.write("\n# Appended by run.py: locally generated signing secrets.\n")
        for key in missing:
            fh.write(f"{key}={secrets.token_hex(32)}\n")


def ensure_env() -> None:
    """Create .env with safe development defaults, or repair an existing one.

    Razorpay keys are left EMPTY on purpose. With no credentials the app
    runs on its simulated provider and says so everywhere; filling in a
    placeholder that looks like a key would make it claim to be live.
    """
    if ENV_PATH.exists():
        repair_env()
        return

    say("SETUP", ".env missing - generating development defaults")
    ENV_PATH.write_text(
        "# Generated by run.py. Safe for local development.\n"
        "#\n"
        "# Razorpay keys are intentionally EMPTY: with no credentials the\n"
        "# app runs on its simulated provider and labels every order\n"
        "# 'simulated'. Paste your test-mode keys below to exercise the\n"
        "# real api.razorpay.com path.\n"
        "RAZORPAY_KEY_ID=\n"
        "RAZORPAY_KEY_SECRET=\n"
        "RAZORPAY_WEBHOOK_SECRET=\n"
        "\n"
        f"MISSION_HMAC_KEY={secrets.token_hex(32)}\n"
        f"USER_MANDATE_KEY={secrets.token_hex(32)}\n"
        f"APP_API_KEY={secrets.token_hex(32)}\n"
        "\n"
        "# Optional. Without a key the buyer agent uses a deterministic\n"
        "# picker. It holds no money authority either way.\n"
        "OPENROUTER_API_KEY=\n"
        "GEMINI_API_KEY=\n"
        "\n"
        "PORT=8000\n"
        "SELLABLE_BASE_URL=http://127.0.0.1:8000\n"
        "SELLABLE_DB_PATH=data/sellable.db\n",
        encoding="utf-8")
    say("SETUP", "wrote .env (payments will run in SIMULATED mode)")


def venv_python() -> Path:
    if sys.platform == "win32":
        return VENV / "Scripts" / "python.exe"
    return VENV / "bin" / "python"


def ensure_dependencies() -> None:
    """Import-test first; only build a venv if something is actually missing."""
    try:
        import dotenv  # noqa: F401
        import fastapi  # noqa: F401
        import uvicorn  # noqa: F401
        say("SETUP", "dependencies present")
        return
    except ImportError:
        pass

    say("SETUP", "dependencies missing - preparing .venv")
    if not VENV.exists():
        try:
            subprocess.run([sys.executable, "-m", "venv", str(VENV)], check=True)
        except (subprocess.CalledProcessError, OSError) as exc:
            die(f"could not create a virtual environment: {exc}",
                f"run '{sys.executable} -m venv .venv' yourself, activate it, "
                f"then 'pip install -r {REQUIREMENTS}'")

    py = venv_python()
    if not py.exists():
        die(f"virtual environment looks incomplete: {py} is missing",
            "delete the .venv directory and re-run 'python run.py'")

    say("SETUP", "installing pinned dependencies (first run only)")
    proc = subprocess.run([str(py), "-m", "pip", "install", "-q",
                           "-r", str(REQUIREMENTS)],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        die("dependency installation failed:\n" + proc.stderr.strip()[-1500:],
            f"activate .venv and run 'pip install -r {REQUIREMENTS}' to see "
            f"the full output")

    say("SETUP", "restarting under .venv")
    os.execv(str(py), [str(py), *sys.argv])


def sign_demo_missions() -> None:
    script = REPO / "scripts" / "sign_mission.py"
    if not script.exists():
        return
    proc = subprocess.run([sys.executable, str(script)], cwd=str(REPO),
                          capture_output=True, text=True)
    if proc.returncode == 0:
        say("SETUP", "demo missions signed")
    else:
        say("WARN", f"mission signing skipped: {proc.stderr.strip()[:200]}")


# ----------------------------------------------------------------- health

def port_free(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.4)
        return s.connect_ex((host, port)) != 0


def pick_port(host: str, wanted: int, explicit: bool) -> int:
    if port_free(host, wanted):
        return wanted
    if explicit:
        die(f"port {wanted} on {host} is already in use",
            f"stop whatever is using it, or run 'python run.py --port "
            f"{wanted + 1}'")
    for candidate in range(wanted + 1, wanted + 20):
        if port_free(host, candidate):
            say("SETUP", f"port {wanted} busy - using {candidate} instead")
            return candidate
    die(f"no free port found between {wanted} and {wanted + 20}",
        "free a port or pass --port explicitly")
    return wanted


def get_json(url: str, timeout: float = 4.0) -> tuple[int, dict | None]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            body = resp.read()
            try:
                return resp.status, json.loads(body)
            except ValueError:
                return resp.status, None
    except urllib.error.HTTPError as exc:
        return exc.code, None
    except Exception:
        return 0, None


def post_json(url: str, payload: dict | None = None,
              timeout: float = 60.0) -> tuple[int, dict | None]:
    data = json.dumps(payload or {}).encode()
    req = urllib.request.Request(
        url, data=data, method="POST",
        headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            try:
                return resp.status, json.loads(resp.read())
            except ValueError:
                return resp.status, None
    except urllib.error.HTTPError as exc:
        try:
            return exc.code, json.loads(exc.read())
        except Exception:
            return exc.code, None
    except Exception:
        return 0, None


def wait_for_health(base: str, proc: subprocess.Popen,
                    max_seconds: float = 45.0) -> bool:
    deadline = time.time() + max_seconds
    while time.time() < deadline:
        if proc.poll() is not None:
            say("ERROR", f"server exited early with code {proc.returncode}")
            return False
        status, _ = get_json(f"{base}/health", timeout=1.5)
        if status == 200:
            return True
        time.sleep(0.4)
    return False


SMOKE_ENDPOINTS = [
    ("/health", "API is up"),
    ("/audit/verify", "audit chain verifies"),
    ("/gateway/proof", "gateway purity report"),
    ("/executions", "execution state machine"),
    ("/webhook/pending", "webhook lifecycle"),
    ("/", "product page"),
    ("/judge", "judge walkthrough"),
    ("/market", "market state machine"),
]


def smoke(base: str) -> bool:
    say("CHECK", "running smoke checks")
    ok = True
    for path, label in SMOKE_ENDPOINTS:
        status, _ = get_json(f"{base}{path}", timeout=6.0)
        mark = "PASS" if status == 200 else "FAIL"
        if status != 200:
            ok = False
        print(f"  [ {mark} ] {path:<20s} {label}"
              + ("" if status == 200 else f"  (HTTP {status or 'no response'})"))
    return smoke_market(base) and ok


def smoke_market(base: str) -> bool:
    """Drive a whole negotiation, end to end, whatever mode we are in.

    Checking that /market answers 200 would prove almost nothing -- the
    interesting part is whether three merchants can actually be asked for
    offers, priced, ranked, accepted and paid on a machine with no keys
    and no network. So this runs that, and reports which mode it ran in
    rather than asserting a particular one.
    """
    status, opened = post_json(
        f"{base}/market/open",
        {"mission_text": "A complete cricket setup under Rs 6,000",
         "use_llm": True})
    if status != 200 or not opened:
        print(f"  [ FAIL ] {'market negotiation':<20s} "
              f"could not open (HTTP {status or 'no response'})")
        return False

    nid = opened["negotiation_id"]
    mode = opened.get("mode", {})
    steps: list[tuple[str, int, dict | None]] = []
    for label, path in (("round", f"/market/{nid}/round"),
                        ("accept", f"/market/{nid}/accept"),
                        ("settle", f"/market/{nid}/settle")):
        st, body = post_json(f"{base}{path}")
        steps.append((label, st, body))
        if st != 200:
            print(f"  [ FAIL ] {'market ' + label:<20s} "
                  f"HTTP {st or 'no response'}")
            return False

    settled = (steps[-1][2] or {}).get("settlement", {})
    order = settled.get("order", {})
    offers = (steps[0][2] or {}).get("offers", [])
    priced = sum(1 for o in offers if o.get("accepted"))
    print(f"  [ PASS ] {'/market negotiation':<20s} "
          f"{priced}/{len(offers)} offers priced, "
          f"{settled.get('merchant_id', '?')} won at "
          f"{settled.get('amount_display', '?')}")
    print(f"  [ PASS ] {'/market settlement':<20s} "
          f"{order.get('execution_state', '?')} via "
          f"{order.get('provider', '?')} "
          f"({mode.get('merchants_label', '?')})")
    return True


def describe_mode(base: str) -> dict:
    _, data = get_json(f"{base}/diagnostics", timeout=6.0)
    return data or {}


# ------------------------------------------------------------------- main

def main() -> int:
    ap = argparse.ArgumentParser(description="Run SELLABLE.")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=None)
    ap.add_argument("--no-browser", action="store_true")
    ap.add_argument("--check", action="store_true",
                    help="verify and exit instead of serving")
    args = ap.parse_args()

    print("=" * 72)
    print("  SELLABLE - autonomous commerce without autonomous money")
    print("=" * 72)

    check_python()
    ensure_env()
    ensure_dependencies()
    sign_demo_missions()

    explicit_port = args.port is not None
    port = pick_port(args.host, args.port or 8000, explicit_port)
    base = f"http://{args.host}:{port}"

    env = {**os.environ, "PORT": str(port), "SELLABLE_BASE_URL": base}
    say("BOOT", f"starting server on {base}")
    proc = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "apps.api.main:app",
         "--host", args.host, "--port", str(port)],
        cwd=str(REPO), env=env)

    try:
        if not wait_for_health(base, proc, max_seconds=45.0):
            proc.terminate()
            proc.wait(timeout=10)
            die("the server did not become healthy within 45 seconds",
                "re-run with the server in the foreground to see the "
                "traceback: python -m uvicorn apps.api.main:app --reload")

        say("BOOT", "server healthy")
        checks_ok = smoke(base)

        diag = describe_mode(base)
        payments = diag.get("payments", {})
        provider = payments.get("provider", "unknown")
        ai = diag.get("ai", {})

        print()
        print("-" * 72)
        print(f"  PAYMENTS   {provider}")
        print(f"             {payments.get('provider_description', '')}")
        print(f"  AGENT      {ai.get('llm_model', 'unknown')}")
        print(f"  GATEWAY    {diag.get('core', {}).get('gateway_rules_registered', '?')}"
              f" deterministic rules, audit chain verified="
              f"{diag.get('core', {}).get('audit_chain_verified')}")
        print("-" * 72)
        print(f"  PRODUCT    {base}/")
        print(f"  JUDGE      {base}/judge")
        print(f"  API DOCS   {base}/docs")
        print("-" * 72)
        if provider == "simulated":
            print("  Payments are SIMULATED: no Razorpay credentials are")
            print("  configured, so no network call is made and every order id")
            print("  is prefixed order_sim_. Add test-mode keys to .env to")
            print("  exercise the real api.razorpay.com path.")
            print("-" * 72)

        if args.check:
            proc.terminate()
            proc.wait(timeout=10)
            print("  RESULT     " + ("PASS" if checks_ok else "FAIL"))
            return 0 if checks_ok else 1

        if not checks_ok:
            say("WARN", "some smoke checks failed - the server is still "
                        "running so you can investigate")

        if not args.no_browser:
            try:
                webbrowser.open(f"{base}/")
            except Exception:
                pass

        print("  Ctrl+C to stop.")
        proc.wait()
        return 0
    except KeyboardInterrupt:
        print()
        say("STOP", "shutting down")
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
